### ISSUE TITLE
cb is not a function

### ISSUE THREAD

**Issue by thoriqazzikraa** [Phantom8015/stable-diffusion-cjs#1]
![Screenshot_2023-05-29-15-36-56-03_61c78dc80ee02b53007c815fefe993e3](https://github.com/Phantom8015/stable-diffusion-cjs/assets/89589243/cadb27e5-e0bb-4d2d-b322-cca889c1ea56)

**Comment by Phantom8015** [comment]
Sorry for the late reply but to fix that issue try reinstalling the package.

**Comment by thoriqazzikraa** [comment]
> Sorry for the late reply but to fix that issue try reinstalling the package.

still same

**Comment by Phantom8015** [comment]
Thank you for replying, I will look into this issue as soon as possible, while it is still happening have you tried using the ejs version?
